version: "3.3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sifre123
    volumes:
      - mysqldata:/var/lib/mysql
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
  yaridm:
    build: .
    ports:
      - 80:8080
    volumes:
      - yardimdata:/upload

volumes:
  mysqldata:
  yardimdata: